# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the eXtended Syscall (XSC) driver
#

obj-$(CONFIG_XSC) += xsc_core.o xsc_consume_fs.o xsc_consume_net.o \
		     xsc_consume_timer.o xsc_consume_sync.o xsc_exec.o
